function varargout = newMask(varargin)

global MolList AtomList fMeasData handles

fig = figure;
set( fig, 'Name', 'MS/MS-Correction (natural Isotope elemination)', 'Menubar', 'none', 'Position', [100 100 910 600] );

if nargin == 0
   
   if nargout > 0
      varargout{1} = fig;
   end
   
   set(fig,'Color', get(0,'defaultUicontrolBackgroundColor'));

   handles.edMolName = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '',...
      'Position', [10 530 200 25], 'Callback', 'edMolName_Callback', 'Tag', 'edMolName', 'HorizontalAlignment', 'left' );
   handles.tMolName = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'Fragment Name',...
      'Position', [10 560 200 15], 'HorizontalAlignment', 'left' );
   
   handles.edMolSumForm = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '',...
      'Position', [10 480 200 25], 'Callback', 'edSumForm_Callback', 'Tag', 'edMolSumForm', 'HorizontalAlignment', 'left' );
   handles.tMolName = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'Sum Form (precursor, w/o derivat.)',...
      'Position', [10 510 200 15], 'HorizontalAlignment', 'left' );
   

   handles.edDerSumForm = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '',...
      'Position', [10 430 200 25], 'Callback', 'edSumForm_Callback', 'Tag', 'edMolSumForm', 'HorizontalAlignment', 'left' );
   handles.tDerName = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'Precursor ion derivat. sum form',...
      'Position', [10 460 200 15], 'HorizontalAlignment', 'left' );

   handles.bNewMol = uicontrol( 'Parent', fig, 'Style', 'Pushbutton', 'String', 'New',...
      'Position', [10 400 60 20], 'Callback', 'bNewMol_Callback', 'Tag', 'bNewMol' );
   handles.bCopyMol = uicontrol( 'Parent', fig, 'Style', 'Pushbutton', 'String', 'Copy',...
      'Position', [80 400 60 20], 'Callback', 'bCopyMol_Callback', 'Tag', 'bCopyMol' );
   handles.bDelMol = uicontrol( 'Parent', fig, 'Style', 'Pushbutton', 'String', 'Delete',...
      'Position', [150 400 60 20], 'Callback', 'bDelMol_Callback', 'Tag', 'bDelMol' );
   
   handles.ListMol = uicontrol( 'Parent', fig, 'Style', 'ListBox', 'String', {},...
      'Position', [10 70 200 300], 'Callback', 'ListMol_Callback', 'Tag', 'ListMol' );
   
   handles.bSaveListMol = uicontrol( 'Parent', fig, 'Style', 'Pushbutton', 'String', 'Save List',...
      'Position', [10 40 90 20], 'Callback', 'bSaveListMol_Callback', 'Tag', 'bSaveListMol' );
   
   handles.bLoadListMol = uicontrol( 'Parent', fig, 'Style', 'Pushbutton', 'String', 'Load List',...
      'Position', [120 40 90 20], 'Callback', 'bLoadListMol_Callback', 'Tag', 'bLoadListMol' );
   
   handles.tFListMol = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '', 'Enable', 'inactive', ...
      'Position', [10 10 200 25] );

   handles.edSepForm = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '',...
      'Position', [230 480 200 25], 'Callback', 'edSumForm_Callback', 'Tag', 'edSepForm', 'HorizontalAlignment', 'left' );
   handles.txt = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'neutral loss sum form:',... 
       'Position', [230 510 200 15], 'HorizontalAlignment', 'left' );
   
   handles.edC = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '',...
      'Position', [230 430 200 25], 'Callback', 'edSumForm_Callback', 'Tag', 'edC', 'HorizontalAlignment', 'left' );
   handles.txt = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'Product ion contains C (array)',...
      'Position', [230 460 200 15], 'HorizontalAlignment', 'left' );

   handles.frame = uicontrol( 'Parent', fig, 'Style', 'Frame', ...
      'Position', [230+240 415+90 210 65] );

   handles.tC = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'C',...
      'Position', [230+245 450+90 15 20] );
   handles.tH = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'H',...
      'Position', [280+245 450+90 15 20] );
   handles.tO = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'O',...
      'Position', [330+245 450+90 15 20] );
   handles.tN = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'N',...
      'Position', [230+245 420+90 15 20] );
   handles.tP = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'P',...
      'Position', [280+245 420+90 15 20] );
   handles.tS = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'S',...
      'Position', [330+245 420+90 15 20] );
   handles.tSi = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'Si',...
      'Position', [380+245 420+90 30 20] );
   handles.nC = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', '0',...
      'Position', [245+245 450+90 25 20], 'Tag', 'nC' );
   handles.nH = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', '0',...
      'Position', [295+245 450+90 25 20], 'Tag', 'nH' );
   handles.nO = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', '0',...
      'Position', [345+245 450+90 25 20], 'Tag', 'nO' );
   handles.nN = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', '0',...
      'Position', [245+245 420+90 25 20], 'Tag', 'nN' );
   handles.nP = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', '0',...
      'Position', [295+245 420+90 25 20], 'Tag', 'nP' );
   handles.nS = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', '0',...
      'Position', [345+245 420+90 25 20], 'Tag', 'nS' );
   handles.nSi = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', '0',...
                            'Position', [405+245 420+90 25 20], 'Tag', 'nSi' );
   
   handles.tm0 = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'Precursor m+0', 'HorizontalAlign', 'left', ...
                            'Position', [230+210 390+80 80 20] );
   handles.m0 = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', '0',...
                           'Position', [230+210+80 390+80 30 20], 'Tag', 'm0' );
   
   handles.tm0f = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'Product m+0', 'HorizontalAlign', 'left',...
                             'Position', [230+210+120 390+80 90 20] );
   handles.m0f = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', '0',...
                            'Position', [230+210+210 390+80 40 20], 'Tag', 'm0f' );

   handles.tNoiseMean = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'Hat: Bias', 'HorizontalAlign', 'left', ...
      'Position', [475 430 70 20] );
   handles.edNoiseMean = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '0', 'HorizontalAlign', 'right',...
      'Position', [540 430 40 25] );
   handles.tNoiseDev = uicontrol( 'Parent', fig, 'Style', 'Text', 'String', 'Noise', 'HorizontalAlign', 'right', ...
      'Position', [590 430 40 20] );
   handles.edNoiseDev = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '0', 'HorizontalAlign', 'right',...
      'Position', [635 430 40 25] );
   
   handles.ListMeas = uicontrol( 'Parent', fig, 'Style', 'ListBox', 'String', {},  ...
      'Position', [230 70 200 350], 'Tag', 'ListMeas', 'FontName', 'FixedWidth', 'Callback', 'markMeas' );
  
   handles.ListMeas_detail = uicontrol( 'Parent', fig, 'Style', 'ListBox', 'String', {}, 'Enable', 'inactive', ...
      'Position', [230+245 70 200 350], 'FontName', 'FixedWidth' );

   handles.bFLoadMeas = uicontrol( 'Parent', fig, 'Style', 'Pushbutton', 'String', 'Load Measurements',...
      'Position', [230 40 150 22], 'Callback', 'bFLoadMeas_Callback', 'Tag', 'bFLoadMeas' );
      
   handles.edPMeas = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '',...
      'Position', [230 10 400 25], 'Callback', 'edFMeas_Callback', 'Tag', 'edPMeas', 'HorizontalAlignment', 'left' );
   
%   handles.edFMeas = uicontrol( 'Parent', fig, 'Style', 'Edit', 'String', '',...
%      'Position', [700 10 200 25], 'Callback', 'edFMeas_Callback', 'Tag', 'edFMeas', 'HorizontalAlignment', 'left' );
   
   handles.bRunCorr = uicontrol( 'Parent', fig, 'Style', 'Pushbutton', 'String', 'RUN Correction',...
      'Position', [700 540 200 30], 'Callback', 'bRunCorr_Callback', 'Tag', 'bRunCorr' );

   handles.bCalcNat = uicontrol( 'Parent', fig, 'Style', 'Pushbutton', 'String', 'Natural Distribution',...
      'Position', [700 500 200 30], 'Callback', 'bNatDist_Callback', 'Tag', 'bNat' );

   handles.bRunCorrM = uicontrol( 'Parent', fig, 'Style', 'Pushbutton', 'String', 'RUN for all fragments',...
      'Position', [700 460 200 30], 'Callback', 'bRunCorrM_Callback', 'Tag', 'bRunCorr' );
   
   handles.ListCorr = uicontrol( 'Parent', fig, 'Style', 'ListBox', 'String', {},...
      'Position', [700 70 200 300], 'Tag', 'ListCorr', 'FontName', 'FixedWidth' );
   
   ListMol_Callback;
   
elseif ischar(varargin{1}) % INVOKE NAMED SUBFUNCTION OR CALLBACK
   
   try
      if (nargout)
         [varargout{1:nargout}] = feval(varargin{:}); % FEVAL switchyard
      else
         feval(varargin{:}); % FEVAL switchyard
      end
   catch
      disp(lasterr);
   end
   
end
